[package]
authors = ["Meta"]
description = "Inspect rust object tree and output it as flamegraph"
documentation = "https://docs.rs/allocative"
edition = "2021"
license = { workspace = true }
name = "allocative"
repository = "https://github.com/facebookexperimental/allocative"
version = "0.3.2"

[dependencies]
allocative_derive = { path = "../allocative_derive", version = "=0.3.2" }

ctor = { workspace = true }

anyhow = { version = "1.0.65", optional = true }
bumpalo = { version = "3.15.0", optional = true }
compact_str = { version = "0.6.1", optional = true }
dashmap = { version = "5.5.3", optional = true }
either = { version = "1.10", optional = true }
futures = { version = "0.3.30", optional = true }
hashbrown = { version = "0.14.3", features = ["raw"], optional = true }
indexmap = { version = "1.9.1", optional = true }
num-bigint = { version = "0.4.3", optional = true }
once_cell = { version = "1.19.0", optional = true }
parking_lot = { version = "0.12.1", optional = true }
prost-types = { version = "0.12.3", optional = true }
relative-path = { version = "1.7.0", optional = true }
serde_json = { version = "1.0.113", optional = true }
slab = { version = "0.4.9", optional = true }
smallvec = { version = "1.13.0", optional = true }
sorted_vector_map.optional = true
# @oss-disable: sorted_vector_map.path = "../../../common/rust/shed/sorted_vector_map"
sorted_vector_map.version = "0.1"
tokio = { version = "1.36", optional = true, features = ["sync"] }
triomphe = { version = "0.1.8", optional = true }

[dev-dependencies]
inferno = { version = "0.11.11", default-features = false }
